[phases.setup]
nixPkgs = ["python310", "nodejs_18"]

[phases.install]
cmds = [
  "pip install pipenv",
  "pipenv install --system --deploy"
]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn medilink.wsgi:application --bind 0.0.0.0:$PORT"
